# Generated by Django 3.0.8 on 2020-07-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='opis',
            field=models.CharField(default='Opis profilu', max_length=255),
            preserve_default=False,
        ),
    ]
